---
name: Net-Whois-RIPE
version: 1.23
author: ~
abstract: ~
license: gpl
requires:
  IO: 1.2
  Test::More: ~
provides:
  Net::Whois::RIPE:
    file: lib/Net/Whois/RIPE.pm
    version: 1.04
  Net::Whois::RIPE::Iterator:
    file: lib/Net/Whois/RIPE/Iterator.pm
    version: 1.01
  Net::Whois::RIPE::Object:
    file: lib/Net/Whois/RIPE/Object.pm
    version: 1.03
  Net::Whois::RIPE::Object::Template:
    file: lib/Net/Whois/RIPE/Object/Template.pm
    version: 1.01
generated_by: Module::Build version 0.2612
