---
name: Net-Whois-RIPE
version: 1.31
author: []
abstract: implementation of RIPE Whois.
license: gpl
resources:
  license: http://opensource.org/licenses/gpl-license.php
requires:
  Carp: ~
  IO: 1.2
  Test::More: ~
provides:
  Net::Whois::RIPE:
    file: lib/Net/Whois/RIPE.pm
    version: 1.30
  Net::Whois::RIPE::Iterator:
    file: lib/Net/Whois/RIPE/Iterator.pm
    version: 1.30
  Net::Whois::RIPE::Object:
    file: lib/Net/Whois/RIPE/Object.pm
    version: 1.31
  Net::Whois::RIPE::Object::Template:
    file: lib/Net/Whois/RIPE/Object/Template.pm
    version: 1.30
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
