--- #YAML:1.0
name:               Net-Whois-RIPE
version:            2.00001
abstract:           a pure-Perl implementation of the RIPE Database client.
author:
    - Luis Motta Campos <lmc@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
