--- #YAML:1.0
name:               Net-Whois-RIPE
version:            2.00011
abstract:           a pure-Perl implementation of the RIPE Database client.
author:
    - Luis Motta Campos <lmc@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Exception:  0
requires:
    Iterator:        0
    Iterator::Util:  0
    perl:            5.006
    Test::More:      0
resources:
    bugtracker:  https://github.com/arhuman/Net-Whois-RIPE/issues
    repository:  https://github.com/arhuman/Net-Whois-RIPE
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
